{
 "title": "Interface Optics Monitoring",
 "description": "DOM Rx Power, Tx Power, Temperature",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Site",
    "query": "show tag values from ifdom_rxpower_status with key = \"site\""
   },
   {
    "name": "device_role",
    "label": "Device Role",
    "query": "SHOW TAG VALUES FROM \"ifdom_rxpower_status\" WITH KEY = \"role\" WHERE \"site\" =~ /^$site$/"
   },
   { "name": "re_if_name", "label": "Interface Regex" },
   { "name": "rxpower_threshold", "label": "Rx Power Threshold", "query": "-19" }
  ]
 },
 "panels": [
  { "title": "Device Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(host) from (select role,host,last(value) from ifdom_rxpower where $timeFilter and\n \"site\" =~ /${site:regex}/ and \"role\" =~ /^${device_role:regex}$/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Count by Role",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(host) from (select role,host,last(value) from ifdom_rxpower where $timeFilter and\n \"site\" =~ /${site:regex}/ and \"role\" =~ /^${device_role:regex}$/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by role,host) group by role\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "content": "\n# Optics Rx Power\n\n\n",
   "targets": [
    { "egressoverride": "average", "labeltype": "default", "rolluptype": "automatic" }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (\n   select * from \"ifdom_rxpower_status\" \n      where $timeFilter and value = 0 and\n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\n     group by host,if_name limit 1\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (select * from \"ifdom_rxpower_status\" where $timeFilter and value = 1 and\n \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alert",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (select * from \"ifdom_rxpower_status\" \nwhere $timeFilter and value = 2 and \n \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "content": "\n# Optics Tx Power\n\n\n",
   "targets": [
    { "egressoverride": "average", "labeltype": "default", "rolluptype": "automatic" }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (\n   select * from \"ifdom_txpower_status\" \n      where $timeFilter and value = 0 and\n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\n      group by host,if_name limit 1\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (select * from \"ifdom_temp_status\" where $timeFilter and value = 1 and\n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alert",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (select * from \"ifdom_temp_status\" \nwhere $timeFilter and value = 2 and \n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 7 },
   "content": "\n# Optics Temperature\n\n\n",
   "targets": [
    { "egressoverride": "average", "labeltype": "default", "rolluptype": "automatic" }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (\n   select * from \"ifdom_temp_status\" \n      where $timeFilter and value = 0 and \n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\n      group by host,if_name limit 1\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (select * from \"ifdom_txpower_status\" where $timeFilter and value = 1 and\n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alert",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(*)  from (select * from \"ifdom_txpower_status\" \nwhere $timeFilter and value = 2 and \n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Rx Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Rx Power <= ${rxpower_threshold} dBm",
   "type": "graph",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_host:$tag_if_name - $tag_if_desc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select value\nfrom \"ifdom_rxpower\" where $timeFilter and\n   value <= ${rxpower_threshold} and\n    \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\n   group by host,if_name,if_desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attention! Rx Power List",
   "type": "table",
   "gridPos": { "h": 19, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "if_name" ], "type": "tag" },
      { "params": [ "if_desc" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifdom_rxpower_status",
     "query": " select last(value),if_desc,role,site from \"ifdom_rxpower_status\" \nwhere $timeFilter and value > 0  \nand \"site\" =~ /${site:regex}/ and \"role\" =~ /${device_role:regex}/ and \"if_name\" =~ /${re_if_name:raw}/\ngroup by host,if_name limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}